# development:
#   adapter: postgresql
#   database: openseat1
#   host: 127.0.0.1
#   pool: 5
#   timeout: 5000


development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: postgres
  username: postgres
  password: 123321
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: postgres
  password: 123321
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: postgres
  password: 123321
  pool: 5
